- name: k8s-master-machine-config
  hosts: k8s-master
  become: 'yes'
  become_user: 'k8s-admin'
  tasks:
    - name: copy the k8s manifest files from anisble to k8s-master
      copy: src=./ci-cd-files/k8s-db-files dest=./k8s-db-files
