apiVersion: v1
kind: Secret
metadata: 
 name: weshopify-app-config-secrete
 labels: 
  secrete: weshopify-app-config-secrete
 namespace: weshopify-app-ns
data:
 #DB_USER_NAME_VALUE: root 
 DB_USER_NAME_VALUE: cm9vdA==
 DB_PASSWORD_VALUE: cm9vdA==
type: Opaque